name: fvdb_build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - ca-certificates
  - certifi
  - cmake
  - cuda-compiler
  - cuda-nvrtc-dev
  - cuda-nvtx-dev
  - cuda-version=13.0
  - cxx-compiler
  - gcc_linux-64=14.3
  - git
  - gxx_linux-64=14.3
  - libcublas-dev
  - libcusolver-dev
  - libcusparse-dev
  - libpng
  - linkify-it-py
  - make
  - myst-parser
  - ninja
  - numpy
  - openssl
  - pkg-config
  - pybind11
  - python=3.12
  - pytorch-gpu=2.13.0
  - scikit-build-core
  - setuptools>=68.2.2
  - sphinx_rtd_theme
  - sphinx>=7.0.0
  - zlib
platforms:
  - linux-64
