name: fvdb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - boto3
  - ca-certificates
  - ccache
  - certifi
  - clang-18
  - clang-format-18
  - clang-tools=21
  - cmake
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-nvrtc-dev
  - cuda-nvtx-dev
  - cuda-version=13.0
  - cxx-compiler
  - einops
  - gcc_linux-64=14.3
  - gh
  - git
  - gitpython
  - gxx_linux-64=14.3
  - ipykernel
  - ipython
  - jupyterlab
  - libclang
  - libcublas-dev
  - libcurand-dev
  - libcusolver-dev
  - libcusparse-dev
  - libpng
  - linkify-it-py
  - make
  - matplotlib
  - msgpack-python
  - myst-parser
  - nbmake
  - ninja
  - numpy
  - open-clip-torch
  - openssl
  - openusd>=26.03
  - pandas
  - parameterized
  - pip
  - pkg-config
  - polyscope
  - psutil
  - py-opencv>=4.10[build=headless*]
  - py-openimageio
  - pybind11
  - pyrender
  - pytest-benchmark
  - python=3.12
  - pytorch-gpu=2.13.0
  - rich
  - sam2
  - scikit-build-core
  - scikit-image
  - seaborn
  - setuptools>=68.2.2
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - tensorboard
  - tqdm
  - zlib
    ## 3dgs
  - gdal
  - pillow
  - pyproj
  - pyyaml
  - scikit-learn
  - srt
  - torchvision
  - tyro
  - utm
  - pip:
    - point-cloud-utils
    - pytest-markdown-docs
    ## 3dgs tests
    - dlnr_lite
