name: fvdb_learn
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - ca-certificates
  - certifi
  - cuda-version=13.0
  - fvdb-core
  - git
  - ipython
  - jupyterlab
  - linkify-it-py
  - matplotlib
  - numpy
  - openssl
  - pandas
  - parameterized
  - pip
  - pkg-config
  - polyscope
  - pyrender
  - pytest-benchmark
  - python=3.12
  - pytorch-gpu=2.13.0
  - tensorboard
  - tqdm
  ## 3dgs
  - tyro
  - pillow
  - py-opencv>=4.10[build=headless*]
  - pyyaml
  - scikit-learn
  - torchvision
  - tyro
  - viser
  - pip:
    - point-cloud-utils
