name: fvdb_test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - ca-certificates
  - certifi
  - cmake
  - cuda-version=13.0
  - libpng
  - ninja
  - matplotlib
  - numpy
  - openssl
  - parameterized
  - pip>=23.3.1
  - pkg-config
  - polyscope
  - pytest
  - pytest-benchmark
  - python=3.12
  - pytorch-gpu=2.13.0
  - tqdm
  - zlib
  - ipykernel
  - nbmake
  - pip:
    - pytest-markdown-docs
    - point-cloud-utils
platforms:
  - linux-64
